joint_traj_controller:
  type: "position_controllers/JointTrajectoryController"

  joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6

  constraints:
      goal_time: 5.0
      stopped_velocity_tolerance: 3.0
      joint_1: {trajectory: &trajectory_pos_constraint 0.2, goal:  &goal_pos_constraint 0.1}
      joint_2: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      joint_3: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      joint_4: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      joint_5: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}
      joint_6: {trajectory: *trajectory_pos_constraint, goal: *goal_pos_constraint}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
